name: valowiki
description: ValoWiki

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  mockito: ^5.4.2
  intl: any
  sqlite3: ^2.1.0
  get_it: ^7.6.4
  flutter_svg: ^2.0.7
  flutter_localization: ^0.1.14
  shared_preferences: ^2.2.1
  logging: ^1.2.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/valorant_font.ttf
